### ISSUE TITLE
Alignment oddities

### ISSUE THREAD

**Issue by ecm-pushbx** [joshudson/dossuperfloppy#1]
In this bit you hardcoded the alignment rather than using the `align` directive: https://github.com/joshudson/dossuperfloppy/blob/ae2acda172f6f19c9dadffd9e02aa1bb17c1b60e/patchdos.asm#L31

While checking the other uses of alignment in the repo I came across a use of `align 2, db $`. Perhaps you wanted `align 2, db '$'` there? https://github.com/joshudson/dossuperfloppy/blob/ae2acda172f6f19c9dadffd9e02aa1bb17c1b60e/formathd.asm#L1041

**Comment by joshudson** [comment]
So I did in fact fix this issue. The SSD tools under development are coming along nicely. I need to read up on the way README works in github before I can make a release. README.TXT needs to be split and renamed. Everything will probably happen along with the first release of the SSD tools.
