### ISSUE TITLE
Bugs in hdgeometry: Wrong function number, cylinders extracted wrongly

### ISSUE THREAD

**Issue by ecm-pushbx** [joshudson/dossuperfloppy#2]
As noted on RC stack exchange: https://retrocomputing.stackexchange.com/questions/27465/rufus-freedos-option-for-cf-is-not-bootable#comment97611_27466

> @Joshua I don't think calling INT 13H with AH=0 returns the geometry, or does it? At least AH=8 would. – 
[Justme](https://retrocomputing.stackexchange.com/users/11656/justme)

Also the calculation to get the amount of cylinders is wrong: https://github.com/joshudson/dossuperfloppy/blob/ae2acda172f6f19c9dadffd9e02aa1bb17c1b60e/hdgeometry.asm#L32

The `and al, 0C0h` needs to go before the `rol` rotations. And you forgot an `inc ax` once the bits are all placed where they belong.

I tested your current revision of this program [in my bootable debugger](https://pushbx.org/ecm/download/ldebug.zip). To test it repeatedly I created a small scriptlet:

`rc.replace boot protocol chain minpara 1 checkvalue 0 hdgeom.bin; g 7C12; r ah 8; t; h as bytes (ch+( (cl&C0) << 2)+1) * (cl&3F) * (dh+1) * #512`

Then I can use the `rc` command to run the entire scriptlet. (Before continuing with a `g` command I also connect to the serial port and enable the int 8 hook using a command `install timer, serial`. This allows to break back into the debugger using a double Control-C on serial input once execution goes into your infinite loop.)

This correctly lists the size of a boot diskette as 1440 KiB (80 cylinders * 2 heads * 18 sectors) but your program needs the fixes I described to display "80 cylinders".

**Comment by ecm-pushbx** [comment]
You could also add a `stc` before the int 13h function 08h call. In my programs I also pre-init `cx` to zero and verify that the maximum sector number returned by the call is non-zero: https://hg.pushbx.org/ecm/ldosboot/file/9c4923acc2be/boot.asm#l1226

**Comment by joshudson** [comment]
What's funny is I tested this. Apparently the random garbage turned out to be correct enough to the disk I had that I didn't notice.

**Comment by ecm-pushbx** [comment]
Yeah, that's why I changed [my bootimg script](https://hg.pushbx.org/ecm/bootimg) command from some bespoke, small-FAT32 MBR partitioned image to a normal 90mm style, 1440 KiB (2880 sectors) unpartitioned diskette image for this test.

**Comment by joshudson** [comment]
; Note that while the original PC BIOS doesn't support this function
	;  (for its diskettes), it does properly return the error code 01h.
	; https://sites.google.com/site/pcdosretro/ibmpcbios (IBM PC version 1)

Oh fun. But I'm only working with hard disks.

**Comment by joshudson** [comment]
Pushed fixes; turns out my system returns something really close to the actual geometry for the last disk when int 13h ah=00h is called.

**Comment by ecm-pushbx** [comment]
Hey, you even found another bug in the display. Good job! https://github.com/joshudson/dossuperfloppy/commit/39fe66e0110c18a6bf07c6c58703e4c011949bd3#diff-b87bd15f737e8757379f7e4c8f43557bb3736cd67892e2c7645e724a82288812L26
