### ISSUE TITLE
Error handling doesn't check range of error code

### ISSUE THREAD

**Issue by ecm-pushbx** [joshudson/dossuperfloppy#3]
https://github.com/joshudson/dossuperfloppy/blob/ae2acda172f6f19c9dadffd9e02aa1bb17c1b60e/patchdos.asm#L138

This code only uses the lower 8 bits of the DOS error code and doesn't check that this value is in range of the error tables at https://github.com/joshudson/dossuperfloppy/blob/ae2acda172f6f19c9dadffd9e02aa1bb17c1b60e/errormsg.asm#L20

This only handles errors 0 to 18 (12h), inclusive.

**Comment by joshudson** [comment]
So this doesn't use the extended error code table at all, but only the return value from int 21h; which is restricted from 0 through 12h. Online source: http://flint.cs.yale.edu/feng/cos/resources/BIOS/Resources/assembly/doserrorcodes.html but I'm pretty sure I pulled this from my textbook.
